=== aliakseishysh/Task2/src/main/resources/data/MedsShemaXMLS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.github.com/setevoybog/Task2"
    xmlns:tns="http://www.github.com/setevoybog/Task2"
    >

    <!-- ROOT ELEMENT -->
    <element name="medicines">
        <complexType>
            <sequence>
                <element name="medicine" type="tns:medicine-type" minOccurs="0" maxOccurs="100"/>
            </sequence>
        </complexType>
    </element>

    <!-- CHILD ELEMENT OF ROOT -->
    <complexType name="medicine-type">
        <sequence>
            <element name="name" type="tns:name-type"/>
            <element name="pharm" type="tns:pharm-type"/>
            <element name="group" type="tns:group-type"/>
            <element name="analogs" type="tns:analogs-type"/>
            <element name="versions" type="tns:versions-type"/>
        </sequence>
        <attribute name="id" type="tns:medicine-id-type" use="required"/>
    </complexType>

    <!-- ID OF SPECIFIC MEDICINE -->
    <simpleType name="medicine-id-type">
        <restriction base="ID">
            <pattern value="i[1-9]{1}[0-9]*"/>
            <maxLength value="9"/>
        </restriction>
    </simpleType>

    <!-- TYPE OF `name` ELEMENT -->
    <simpleType name="name-type">
        <restriction base="string"> 
            <minLength value="1"/>
            <maxLength value="100"/>
        </restriction>
    </simpleType>

    <!-- TYPE OF `analog` ELEMENT -->
    <simpleType name="analog-type">
        <restriction base="string"> 
            <minLength value="1"/>
            <maxLength value="100"/>
        </restriction>
    </simpleType>

    <!-- TYPE OF `pharm` ELEMENT -->
    <simpleType name="pharm-type">
        <restriction base="string"> 
            <minLength value="1"/>
            <maxLength value="100"/>
        </restriction>
    </simpleType>

    <!-- TYPE OF `group` ELEMENT -->
    <simpleType name="group-type">
        <restriction base="string">
            <enumeration value="Vegetotropic medicines"/>
            <enumeration value="Hematotropic medicines"/>
            <enumeration value="Homeopathic medicines"/>
            <enumeration value="Hormones and their antagonists"/>
            <enumeration value="Diagnostic medicines"/>
            <enumeration value="Immunotropic medicines"/>
            <enumeration value="Intermediates medicines"/>
            <enumeration value="Metabolics medicines"/>
            <enumeration value="Neurotropic medicines"/>
            <enumeration value="Non-narcotic analgesics"/>
            <enumeration value="Organotropic medicines"/>
            <enumeration value="Antimicrobial, antiparasitic and antihelminthic medicines"/>
            <enumeration value="Antineoplastic medicines"/>
            <enumeration value="Regenerants and reparants"/>
            <enumeration value="Biologically active food additives"/>
            <enumeration value="Different medicines"/>
        </restriction>
    </simpleType>

    <!-- TYPE OF `analogs` ELEMENT -->
    <complexType name="analogs-type">
        <sequence>
            <element name="analog" type="tns:analog-type" minOccurs="0" maxOccurs="100"/>
        </sequence>
    </complexType>

    <!-- TYPE OF `version` ELEMENT -->
    <complexType name="version-type">
        <sequence>
            <element name="certificate" type="tns:certificate-type"/>
            <element name="package" type="tns:package-type"/>
            <element name="dosages" type="tns:dosages-type"/>
        </sequence>
        <attribute name="distribution-version" use="required" type="tns:distribution-versions-enum-type"/>
    </complexType>

    <!-- TYPE OF `versions` ELEMENT (includes `version`) -->
    <complexType name="versions-type">
        <sequence>
            <element name="version" type="tns:version-type" minOccurs="1" maxOccurs="50"/>
        </sequence>
    </complexType>

    <!-- TYPE OF ATTRIBUTE `version` OF `version` ELEMENT in `versions` ELEMENT -->
    <simpleType name="distribution-versions-enum-type">
        <restriction base="string">
            <enumeration value="ointment"/>
            <enumeration value="cream"/>
            <enumeration value="pills"/>
            <enumeration value="capsules"/>
            <enumeration value="solute"/>
            <enumeration value="injection"/>
            <enumeration value="suspension"/>
            <enumeration value="powder"/>
        </restriction>
    </simpleType>

    <!-- TYPE OF ELEMENT `sertificate` -->
    <complexType name="certificate-type">
        <sequence>
            <element name="certificate-number" type="long"/>
            <element name="certificate-issued-date-time" type="dateTime"/> <!-- The dateTime is specified in the following form "YYYY-MM-DDThh:mm:ss" -->
            <element name="certificate-expires-date-time" type="dateTime"/>
            <element name="certificate-registered-organization" type="string"/>
        </sequence>
    </complexType>

    <!-- TYPE OF ELEMENT `package` -->
    <complexType name="package-type">
        <sequence>
            <element name="package-type" type="tns:package-type-enum-type"/>
            <element name="package-elements-count-in" type="tns:package-elements-count-in-type"/>
            <element name="package-price" type="int"/> <!-- price of package in euro -->
        </sequence>
    </complexType>
    <!-- packages types -->
    <simpleType name="package-type-enum-type">
        <restriction base="string">
            <enumeration value="cell packaging"/>
            <enumeration value="bottle"/>
            <enumeration value="jar"/>
            <enumeration value="ampoules"/>
            <enumeration value="syringe"/>
            <enumeration value="aluminum tubes"/>
        </restriction>
    </simpleType>
    <!-- number of elements in package -->
    <simpleType name="package-elements-count-in-type">
        <restriction base="int">
        </restriction>
    </simpleType>
        
    <!-- TYPE OF `dosages` ELEMENT (includes `dosage`) -->
    <complexType name="dosages-type">
        <sequence>
            <element name="dosage" type="tns:dosage-type" minOccurs="1" maxOccurs="10"/>
        </sequence>
    </complexType>
    <!-- type of element `dosage` -->
    <complexType name="dosage-type">
        <sequence>
            <element name="dosage-description" type="tns:dosage-description-type"/>
            <element name="dosage-active-agent" type="int"/> <!-- amount of active agent in milligrams -->
            <element name="dosage-maximum-use-per-day" type="int"/> <!-- amount of elements in package to use per day -->
        </sequence>
    </complexType>
    <!-- type of element dosage-description -->
    <simpleType name="dosage-description-type">
        <restriction base = "string">
            <maxLength value="1000"/>
        </restriction>
    </simpleType>

</schema>

=== aliakseishysh/Task2/src/main/resources/data/Meds.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:medicines xmlns:tns="Medicines" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Medicines MedsShemaXMLS.xsd ">
	<!-- MEDICINE 1 -->
	<tns:medicine tns:id="i1">   
		<tns:name>IBUPROFEN</tns:name>
		<tns:pharm>MINSK-PHARM</tns:pharm>
		<tns:group>Non-narcotic analgesics</tns:group>
		<tns:analogs>
			<tns:analog>IBUPROFEN-MAX</tns:analog>
			<tns:analog>IBUPROFEN-SUPER-MAX</tns:analog>
		</tns:analogs>
		<tns:versions>
			<tns:version tns:distribution-version="pills">
 				<tns:certificate>
 					<tns:certificate-number>1000000000</tns:certificate-number>
 					<tns:certificate-issued-date-time>2020-01-01T00:00:00</tns:certificate-issued-date-time>
 					<tns:certificate-expires-date-time>2025-01-01T00:00:00</tns:certificate-expires-date-time>
 					<tns:certificate-registered-organization>Minzdrav</tns:certificate-registered-organization>
 				</tns:certificate>
 				<tns:package>
 					<tns:package-type>cell packaging</tns:package-type>
 					<tns:package-elements-count-in>10</tns:package-elements-count-in>
 					<tns:package-price>1</tns:package-price>
 				</tns:package>
 				<tns:dosage>
 					<tns:dosage-active-agent>50</tns:dosage-active-agent>
 					<tns:dosage-maximum-use-per-day>5</tns:dosage-maximum-use-per-day>
 				</tns:dosage>
			</tns:version>
		</tns:versions>
	</tns:medicine>
	
	<!-- MEDICINE 2 -->
	<tns:medicine tns:id="i2">   
		<tns:name>Aleffke</tns:name>
		<tns:pharm>MINSK-PHARM</tns:pharm>
		<tns:group>Homeopathic medicines</tns:group>
		<tns:analogs>
			<tns:analog>Aleffke-MAX</tns:analog>
		</tns:analogs>
		<tns:versions> 
			<tns:version tns:distribution-version="pills">
 				<tns:certificate>
 					<tns:certificate-number>1000000002</tns:certificate-number>
 					<tns:certificate-issued-date-time>2020-01-01T00:00:00</tns:certificate-issued-date-time>
 					<tns:certificate-expires-date-time>2025-01-01T00:00:00</tns:certificate-expires-date-time>
 					<tns:certificate-registered-organization>Minzdrav</tns:certificate-registered-organization>
 				</tns:certificate>
 				<tns:package>
 					<tns:package-type>cell packaging</tns:package-type>
 					<tns:package-elements-count-in>10</tns:package-elements-count-in>
 					<tns:package-price>1</tns:package-price>
 				</tns:package>
 				<tns:dosage>
 					<tns:dosage-active-agent>50</tns:dosage-active-agent>
 					<tns:dosage-maximum-use-per-day>5</tns:dosage-maximum-use-per-day>
 				</tns:dosage>
			</tns:version>
			<tns:version tns:distribution-version="capsules">
 				<tns:certificate>
 					<tns:certificate-number>1000000003</tns:certificate-number>
 					<tns:certificate-issued-date-time>2020-01-01T00:00:00</tns:certificate-issued-date-time>
 					<tns:certificate-expires-date-time>2025-01-01T00:00:00</tns:certificate-expires-date-time>
 					<tns:certificate-registered-organization>Minzdrav</tns:certificate-registered-organization>
 				</tns:certificate>
 				<tns:package>
 					<tns:package-type>jar</tns:package-type>
 					<tns:package-elements-count-in>30</tns:package-elements-count-in>
 					<tns:package-price>10</tns:package-price>
 				</tns:package>
 				<tns:dosage>
 					<tns:dosage-active-agent>50</tns:dosage-active-agent>
 					<tns:dosage-maximum-use-per-day>5</tns:dosage-maximum-use-per-day>
 				</tns:dosage>
			</tns:version>
		</tns:versions>
	</tns:medicine>
	
		<!-- MEDICINE 3 -->
	<tns:medicine tns:id="i3">   
		<tns:name>ILKffk</tns:name>
		<tns:pharm>MINSK-PHARM</tns:pharm>
		<tns:group>Hormones and their antagonists</tns:group>
		<tns:analogs>
		</tns:analogs>
		<tns:versions> 
			<tns:version tns:distribution-version="pills">
 				<tns:certificate>
 					<tns:certificate-number>1000000004</tns:certificate-number>
 					<tns:certificate-issued-date-time>2020-01-01T00:00:00</tns:certificate-issued-date-time>
 					<tns:certificate-expires-date-time>2021-01-01T00:00:00</tns:certificate-expires-date-time>
 					<tns:certificate-registered-organization>Minzdrav</tns:certificate-registered-organization>
 				</tns:certificate>
 				<tns:package>
 					<tns:package-type>ampoules</tns:package-type>
 					<tns:package-elements-count-in>20</tns:package-elements-count-in>
 					<tns:package-price>2</tns:package-price>
 				</tns:package>
 				<tns:dosage>
 					<tns:dosage-active-agent>60</tns:dosage-active-agent>
 					<tns:dosage-maximum-use-per-day>4</tns:dosage-maximum-use-per-day>
 				</tns:dosage>
			</tns:version>
		</tns:versions>
	</tns:medicine>
	
		<!-- MEDICINE 4 -->
	<tns:medicine tns:id="i4">   
		<tns:name>IBUPOF</tns:name>
		<tns:pharm>BREST-PHARM</tns:pharm>
		<tns:group>Non-narcotic analgesics</tns:group>
		<tns:analogs>
			<tns:analog>IBUPOF-MAX</tns:analog>
		</tns:analogs>
		<tns:versions> 
			<tns:version tns:distribution-version="pills">
 				<tns:certificate>
 					<tns:certificate-number>1000000005</tns:certificate-number>
 					<tns:certificate-issued-date-time>2020-01-01T00:00:00</tns:certificate-issued-date-time>
 					<tns:certificate-expires-date-time>2025-01-01T00:00:00</tns:certificate-expires-date-time>
 					<tns:certificate-registered-organization>Minzdrav</tns:certificate-registered-organization>
 				</tns:certificate>
 				<tns:package>
 					<tns:package-type>syringe</tns:package-type>
 					<tns:package-elements-count-in>1</tns:package-elements-count-in>
 					<tns:package-price>100</tns:package-price>
 				</tns:package>
 				<tns:dosage>
 					<tns:dosage-active-agent>500</tns:dosage-active-agent>
 					<tns:dosage-maximum-use-per-day>1</tns:dosage-maximum-use-per-day>
 				</tns:dosage>
			</tns:version>
		</tns:versions>
	</tns:medicine>
	
		<!-- MEDICINE 6 -->
	<tns:medicine tns:id="i5">   
		<tns:name>Sweets</tns:name>
		<tns:pharm>MINSK-Sweet-PHARM</tns:pharm>
		<tns:group>Biologically active food additives</tns:group>
		<tns:analogs>
			<tns:analog>Sweets-MAX</tns:analog>
			<tns:analog>Sweets-Super-MAX</tns:analog>
		</tns:analogs>
		<tns:versions> 
			<tns:version tns:distribution-version="pills">
 				<tns:certificate>
 					<tns:certificate-number>1000000006</tns:certificate-number>
 					<tns:certificate-issued-date-time>2020-01-01T00:00:00</tns:certificate-issued-date-time>
 					<tns:certificate-expires-date-time>2025-01-01T00:00:00</tns:certificate-expires-date-time>
 					<tns:certificate-registered-organization>Minzdrav</tns:certificate-registered-organization>
 				</tns:certificate>
 				<tns:package>
 					<tns:package-type>cell packaging</tns:package-type>
 					<tns:package-elements-count-in>10</tns:package-elements-count-in>
 					<tns:package-price>1</tns:package-price>
 				</tns:package>
 				<tns:dosage>
 					<tns:dosage-active-agent>500</tns:dosage-active-agent>
 					<tns:dosage-maximum-use-per-day>100</tns:dosage-maximum-use-per-day>
 				</tns:dosage>
			</tns:version>
			<tns:version tns:distribution-version="powder">
 				<tns:certificate>
 					<tns:certificate-number>1000000007</tns:certificate-number>
 					<tns:certificate-issued-date-time>2020-01-01T00:00:00</tns:certificate-issued-date-time>
 					<tns:certificate-expires-date-time>2025-01-01T00:00:00</tns:certificate-expires-date-time>
 					<tns:certificate-registered-organization>Minzdrav</tns:certificate-registered-organization>
 				</tns:certificate>
 				<tns:package>
 					<tns:package-type>aluminum tubes</tns:package-type>
 					<tns:package-elements-count-in>100</tns:package-elements-count-in>
 					<tns:package-price>100</tns:package-price>
 				</tns:package>
 				<tns:dosage>
 					<tns:dosage-active-agent>500</tns:dosage-active-agent>
 					<tns:dosage-maximum-use-per-day>100</tns:dosage-maximum-use-per-day>
 				</tns:dosage>
			</tns:version>
		</tns:versions>
	</tns:medicine>
	
		<!-- MEDICINE 6 -->
	<tns:medicine tns:id="i6">   
		<tns:name>Lafafa</tns:name>
		<tns:pharm>Paris-PHARM</tns:pharm>
		<tns:group>Diagnostic medicines</tns:group>
		<tns:analogs>
			<tns:analog>Lafafa-MAX</tns:analog>
		</tns:analogs>
		<tns:versions> 
			<tns:version tns:distribution-version="pills">
 				<tns:certificate>
 					<tns:certificate-number>1000000008</tns:certificate-number>
 					<tns:certificate-issued-date-time>2020-01-01T00:00:00</tns:certificate-issued-date-time>
 					<tns:certificate-expires-date-time>2025-01-01T00:00:00</tns:certificate-expires-date-time>
 					<tns:certificate-registered-organization>ParMinzdrav</tns:certificate-registered-organization>
 				</tns:certificate>
 				<tns:package>
 					<tns:package-type>bottle</tns:package-type>
 					<tns:package-elements-count-in>10</tns:package-elements-count-in>
 					<tns:package-price>1</tns:package-price>
 				</tns:package>
 				<tns:dosage>
 					<tns:dosage-active-agent>50</tns:dosage-active-agent>
 					<tns:dosage-maximum-use-per-day>5</tns:dosage-maximum-use-per-day>
 				</tns:dosage>
			</tns:version>
		</tns:versions>
	</tns:medicine>
	
		<!-- MEDICINE 7 -->
	<tns:medicine tns:id="i7">   
		<tns:name>IBUPROJEN</tns:name>
		<tns:pharm>MINSK-PHARM</tns:pharm>
		<tns:group>Neurotropic medicines</tns:group>
		<tns:analogs>
			<tns:analog>IBUPROJEN-MAX</tns:analog>
		</tns:analogs>
		<tns:versions> 
			<tns:version tns:distribution-version="pills">
 				<tns:certificate>
 					<tns:certificate-number>1000000009</tns:certificate-number>
 					<tns:certificate-issued-date-time>2020-01-01T00:00:00</tns:certificate-issued-date-time>
 					<tns:certificate-expires-date-time>2025-01-01T00:00:00</tns:certificate-expires-date-time>
 					<tns:certificate-registered-organization>Minzdrav</tns:certificate-registered-organization>
 				</tns:certificate>
 				<tns:package>
 					<tns:package-type>ampoules</tns:package-type>
 					<tns:package-elements-count-in>10</tns:package-elements-count-in>
 					<tns:package-price>2</tns:package-price>
 				</tns:package>
 				<tns:dosage>
 					<tns:dosage-active-agent>100</tns:dosage-active-agent>
 					<tns:dosage-maximum-use-per-day>1</tns:dosage-maximum-use-per-day>
 				</tns:dosage>
			</tns:version>
